Repository openshift/appliance, pull requests merged in 2023-10, with the labels that each got.

#147 MGMT-14412: Support additional images and operators on build
  docs/appliance-config.md
  docs/user-guide.md
  go.mod
  go.sum
  pkg/asset/appliance/appliance_diskimage.go
  pkg/asset/config/appliance_config.go
  pkg/asset/data/data_iso.go
  pkg/asset/ignition/bootstrap_ignition.go
  pkg/asset/ignition/install_ignition.go
  pkg/asset/registry/registriesconf.go
  pkg/consts/consts.go
  pkg/release/mock_release.go
  pkg/release/release.go
  pkg/release/release_test.go
  pkg/templates/data.go
  pkg/templates/partitions.go
  pkg/templates/scripts/mirror/imageset.yaml.template
  pkg/types/appliance_config_type.go
Labels: approved, lgtm, jira/valid-reference

#148 MGMT-15869: Added a MachineConfig to set core password
  data/services/install/set-core-pass.service.template
  pkg/asset/ignition/bootstrap_ignition.go
  pkg/asset/ignition/install_ignition.go
Labels: approved, lgtm, jira/valid-reference

#149 MGMT-14687: Stop local registry post cluster installation
  data/scripts/bin/stop-local-registry.sh.template
  data/services/common/start-local-registry.service
  data/services/install/stop-local-registry.service
  docs/appliance-config.md
  docs/user-guide.md
  pkg/asset/config/appliance_config.go
  pkg/asset/ignition/install_ignition.go
  pkg/consts/consts.go
  pkg/types/appliance_config_type.go
Labels: approved, lgtm, jira/valid-reference

#150 OSDOCS-8178: linking to Agent docs for configuration reference
  docs/user-guide.md
Labels: approved, lgtm, jira/valid-reference

#151 Update user-guide.md
  docs/user-guide.md
Labels: approved, lgtm, ok-to-test

#152 OSDOCS-8178: (addendum) linking to Agent docs for configuration reference
  docs/user-guide.md
Labels: approved, lgtm, jira/valid-reference

#153 MGMT-15995: fix 'Add custom manifests' doc
  docs/user-guide.md
Labels: approved, lgtm, jira/valid-reference

#154 README cleanups
  README.md
Labels: approved, lgtm

#156 MGMT-15996: added additionalImages example to the user-guide
  docs/user-guide.md
Labels: approved, lgtm, jira/valid-reference

#155 Fix user guide YAML formatting
  docs/user-guide.md
Labels: approved, lgtm

#157 MGMT-16019: fixes for manifests section in user-guide
  docs/user-guide.md
Labels: approved, lgtm, jira/valid-reference

#159 Remove redundand extraManifestsPath const from InstallIgnition
  pkg/asset/ignition/bootstrap_ignition.go
  pkg/asset/ignition/install_ignition.go
Labels: approved, lgtm

#158 user-guide: add some notes on operators sections
  docs/user-guide.md
Labels: approved, lgtm

#160 MGMT-16043: fix Subscription example in user-guide
  docs/user-guide.md
Labels: approved, lgtm, jira/valid-reference

#161 MGMT-15996: added examples to additionalImages in docs
  docs/user-guide.md
Labels: approved, lgtm, jira/valid-reference
