Repository openshift/appliance, pull requests merged in 2023-06, with the labels that each got.

#34 MGMT-14865: Added userCorePass to ApplianceConfig
  README.md
  pkg/asset/config/appliance_config.go
  pkg/asset/ignition/bootstrap_ignition.go
  pkg/types/appliance_config_type.go
Labels: jira/valid-reference

#30 MGMT-14285: added validation to ApplianceConfig
  README.md
  pkg/asset/config/appliance_config.go
  pkg/types/appliance_config_type.go
Labels: jira/valid-reference

#36 readme: fix run section for container image
  README.md
Labels: lgtm

#38 MGMT-14917: Fix rhcos grub menu item removal
  pkg/templates/scripts/guestfish/guestfish.sh.template
Labels: jira/valid-reference

#39 MGMT-14920: check if clean command should be invoked
  cmd/build.go
  pkg/asset/appliance/appliance_diskimage.go
Labels: jira/valid-reference

#40 MGMT-14872: generate openshift-install download URL
  cmd/build.go
  go.mod
  go.sum
  pkg/asset/ignition/recovery_ignition.go
  pkg/asset/installer/installer_binary.go
  pkg/installer/installer.go
  pkg/release/release.go
Labels: jira/valid-reference

#44 MGMT-15032: Appliance build prints should specify OCP version
  pkg/asset/data/data_iso.go
Labels: jira/valid-reference

#48 MGMT-15006: add 'Configuration ISO' section to readme
  README.md
Labels: approved, lgtm, jira/valid-reference

#49 MGMT-15052: removed tabs from appliance-config template
  pkg/asset/config/appliance_config.go
Labels: approved, lgtm, jira/valid-reference

#52 MGMT-15042: fix build completion message
  cmd/build.go
Labels: approved, lgtm, jira/valid-reference

#50 appliance-config: fix minimal release version validation
  pkg/asset/config/appliance_config.go
Labels: approved, lgtm

#51 MGMT-15053: fallback to stable release channel
  pkg/asset/config/appliance_config.go
Labels: approved, lgtm, jira/valid-reference

#47 MGMT-15007: support multi-node cluster installation
  data/scripts/bin/prepare-cluster-installation.sh.template
  data/scripts/bin/update-hosts.sh.template
  data/services/pre-install.service
  data/services/update-hosts.service
  pkg/asset/ignition/bootstrap_ignition.go
Labels: approved, lgtm, jira/valid-reference

#53 MGMT-15124: fix install-config name change
  pkg/asset/ignition/unconfigured.ign
  pkg/asset/manifests/infraenv.go
Labels: approved, lgtm, jira/valid-reference

#55 MGMT-15042: fix generate-config completion message
  cmd/config.go
Labels: approved, lgtm, jira/valid-reference

#54 Makefile: changed repo to edge-infrastructure
  Makefile
Labels: approved, lgtm
