Repository openshift/appliance, pull requests merged in 2023-09, with the labels that each got.

#133 Move debug flags to buildOpts struct
  cmd/build.go
  cmd/main.go
Labels: approved, lgtm

#137 user-guide: note about pull-secret in disconnected env
  docs/user-guide.md
Labels: approved, lgtm

#138 MGMT-15698: Document how to add custom manifests
  docs/user-guide.md
Labels: approved, lgtm, jira/valid-reference

#139 MGMT-15673: set core pass on installation step
  data/services/install/set-core-pass.service.template
  pkg/asset/ignition/bootstrap_ignition.go
  pkg/asset/ignition/install_ignition.go
  pkg/templates/data.go
Labels: approved, lgtm, jira/valid-reference

#140 MGMT-15176: Adds a user facing Appliance configuration document
  docs/appliance-config.md
  docs/user-guide.md
Labels: approved, lgtm, jira/valid-reference

#141 MGMT-15739: Fallback to OCP 4.14 when version is missing from Cincinnati
  docs/appliance-config.md
  docs/user-guide.md
  pkg/asset/config/appliance_config.go
  pkg/consts/consts.go
  pkg/graph/graph.go
  pkg/graph/graph_test.go
Labels: approved, lgtm, jira/valid-reference

#142 MGMT-15280: Set 4.14.0-rc.0 as minimal OCP version
  Dockerfile.openshift-appliance
  data/scripts/bin/get-container-images.sh.template
  docs/user-guide.md
  pkg/asset/ignition/bootstrap_ignition.go
  pkg/asset/ignition/unconfigured.ign
  pkg/consts/consts.go
  pkg/installer/installer.go
  pkg/installer/installer_test.go
  pkg/release/release.go
Labels: approved, lgtm, jira/valid-reference

#143 MGMT-15170: improve errors for appliance-config unmarshal failure
  pkg/asset/config/appliance_config.go
Labels: approved, lgtm, jira/valid-reference

#136 MGMT-15520: Appliance deployment bootable ISO
  cmd/build.go
  data/scripts/bin/deploy.sh.template
  data/services/deploy/deploy.service.template
  docs/images/deploy-iso.gif
  docs/user-guide.md
  go.mod
  go.sum
  pkg/asset/config/deploy_config.go
  pkg/asset/deploy/deploy_iso.go
  pkg/asset/ignition/deploy_ignition.go
  pkg/consts/consts.go
  pkg/fileutil/fileutil.go
  pkg/templates/data.go
Labels: approved, lgtm, jira/valid-reference

#145 Update user-guide.md
  docs/user-guide.md
Labels: approved, lgtm, ok-to-test

#144 MGMT-15759: generate DeployConfig only for deployment ISO
  cmd/build.go
Labels: approved, lgtm

#146 user-guide: fix static networking URL
  docs/user-guide.md
Labels: approved, lgtm
