Repository openshift/appliance, pull requests merged in 2023-05, with the labels that each got.

#3 MGMT-14263: Migrate to openshift/appliance repo
  cmd/build.go
  cmd/clean.go
  cmd/config.go
  cmd/debug.go
  cmd/main.go
  go.mod
  pkg/asset/appliance/appliance_diskimage.go
  pkg/asset/appliance/base_diskimage.go
  pkg/asset/config/appliance_config.go
  pkg/asset/data/data_iso.go
  pkg/asset/ignition/bootstrap_ignition.go
  pkg/asset/ignition/install_ignition.go
  pkg/asset/manifests/clusterimageset.go
  pkg/asset/recovery/base_iso.go
  pkg/asset/recovery/recovery_iso.go
  pkg/asset/registry/registriesconf.go
  pkg/coreos/coreos.go
  pkg/genisoimage/genisoimage.go
  pkg/graph/graph.go
  pkg/log/spinner.go
  pkg/registry/registry.go
  pkg/release/release.go
  pkg/skopeo/skopeo.go
  pkg/templates/data.go
Labels: lgtm, jira/valid-reference

#6 Fix lint errors
  cmd/build.go
  pkg/asset/appliance/base_diskimage.go
  pkg/asset/data/data_iso.go
  pkg/release/release.go
Labels: lgtm

#11 MGMT-14659: Fix spinner nil pointer exception
  pkg/log/spinner.go
Labels: jira/valid-reference

#13 MGMT-14677: Bump to go 1.19
  Dockerfile.openshift-appliance
  Dockerfile.openshift-appliance-build
  go.mod
Labels: jira/valid-reference

#16 MGMT-14647: added file size validation on findInDir
  pkg/asset/config/env_config.go
Labels: lgtm, jira/valid-reference

#17 MGMT-14694: Container image should include skopeo
  Dockerfile.openshift-appliance
Labels: jira/valid-reference

#22 MGMT-14549: Remove UBI from MirrorReleaseImages
  pkg/release/release.go
Labels: jira/valid-reference

#28 Update golangci-lint version and timeout
  Makefile
  hack/setup_env.sh
Labels: lgtm

#18 MGMT-14762: Fix podman
  Dockerfile.openshift-appliance
  Makefile
  README.md
  data/scripts/bin/start-local-registry.sh.template
  pkg/registry/registry.go
  pkg/release/release.go
Labels: jira/valid-reference
