Repository openshift/appliance, pull requests merged in 2024-03, with the labels that each got.

#206 Added documentation for upgrade-tool
  docs/upgrade-tool.md
Labels: approved, lgtm

#208 Update go pkgs
  go.mod
  go.sum
Labels: approved

#209 docs: updates about sshKey property
  README.md
  docs/user-guide.md
Labels: approved

#210 MGMT-17308: Offboard osherdp from maintainers list
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#213 MGMT-17330: Use oc-mirror from stable-4.14
  Dockerfile.openshift-appliance
Labels: approved, jira/valid-reference

#214 Bump to go 1.20
  Dockerfile.openshift-appliance
  Dockerfile.openshift-appliance-build
  go.mod
Labels: approved

#216 MGMT-17345: Dockerfile - update to ubi9
  Dockerfile.openshift-appliance
Labels: approved, jira/valid-reference

#218 MGMT-17368: fix missing virt-resize
  Dockerfile.openshift-appliance
Labels: approved, jira/valid-reference

#219 NO-ISSUE: warning for unsupported OCP version
  pkg/asset/config/appliance_config.go
  pkg/asset/config/env_config.go
Labels: approved, jira/valid-reference
