Repository openshift/appliance, pull requests merged in 2025-05, with the labels that each got.

#377 MGMT-20521: Load extra manifests on cluster startup
  data/scripts/bin/update-hosts.sh.template
Labels: lgtm, jira/valid-reference

#379 Ensure IDMS is split into multiple YAMLs
  pkg/asset/config/env_config.go
  pkg/asset/ignition/bootstrap_ignition.go
  pkg/asset/registry/registriesconf.go
  pkg/consts/consts.go
  pkg/release/release.go
Labels: approved

#380 Register extra manifests according to EnableInteractiveFlow flag
  data/scripts/bin/update-hosts.sh.template
  pkg/asset/ignition/bootstrap_ignition.go
  pkg/templates/data.go
Labels: approved

#382 NO-ISSUE: Increase the start timeout to 30 min
  data/services/common/start-local-registry.service
Labels: approved, jira/valid-reference

#384 Konflux build pipeline service account migration for appliance
  .tekton/appliance-pull-request.yaml
  .tekton/appliance-push.yaml
Labels: approved

#393 MGMT-20590: Support blockedImages property in appliance-config
  docs/appliance-config.md
  docs/user-guide.md
  pkg/asset/config/appliance_config.go
  pkg/release/release.go
  pkg/types/appliance_config_type.go
Labels: approved, jira/valid-reference

#398 MGMT-20574: apply CRs during installation
  data/scripts/bin/apply-operator-crs.sh.template
  data/services/install/apply-operator-crs.service
  docs/user-guide.md
  pkg/asset/ignition/bootstrap_ignition.go
  pkg/asset/ignition/install_ignition.go
  pkg/asset/manifests/operator_crs.go
Labels: approved, lgtm, jira/valid-reference

#404 MGMT-20615: increasing local registry setup timeout to 2.5h
  data/services/common/start-local-registry.service
Labels: approved, lgtm, jira/valid-reference

#407 update mod: httpcache
  go.mod
  go.sum
Labels: approved

#408 MGMT-20715: support ISO level-3 when generating the data image
  pkg/genisoimage/genisoimage.go
Labels: approved, jira/valid-reference
