Repository openshift/appliance, pull requests merged in 2025-09, with the labels that each got.

#522 Revert "Remove tekton dir"
  .tekton/appliance-pull-request.yaml
  .tekton/appliance-push.yaml
Labels: approved

#530 OCPBUGS-61242: fix mount registry data on reboot
  data/scripts/bin/mount-agent-data.sh.template
Labels: jira/severity-moderate, approved, jira/valid-bug, jira/valid-reference

#541 Rebase 4.20
  .tekton/appliance-pull-request.yaml
  .tekton/appliance-push.yaml
  data/scripts/bin/mount-agent-data.sh.template
  data/scripts/bin/stop-local-registry.sh.template
  docs/user-guide.md
  pkg/asset/config/appliance_config.go
  pkg/asset/data/data_iso.go
  pkg/asset/ignition/install_ignition.go
  pkg/consts/consts.go
  pkg/executer/executer.go
  pkg/executer/mock_executer.go
  pkg/registry/registry.go
  pkg/types/appliance_config_type.go
Labels: approved

#543 MGMT-21854: fix registries.conf generation for multiple yaml mirror files
  pkg/asset/registry/registriesconf.go
  pkg/asset/registry/registriesconf_test.go
Labels: approved, lgtm, jira/valid-reference
