Repository openshift/appliance, pull requests merged in 2025-03, with the labels that each got.

#346 Update go mods
  go.mod
  go.sum
Labels: approved

#347 MGMT-19982: support the interactive flow in unconfigured-ignition
  docs/appliance-config.md
  docs/user-guide.md
  pkg/asset/config/appliance_config.go
  pkg/consts/consts.go
  pkg/installer/installer.go
  pkg/installer/installer_test.go
  pkg/types/appliance_config_type.go
Labels: approved, lgtm, jira/valid-reference

#348 Add privileged flag to podman live iso command
  docs/user-guide.md
Labels: approved, lgtm, ok-to-test

#350 MGMT-20132: Use PersistentFlags for debug hidden flags
  cmd/build.go
Labels: approved, lgtm, jira/valid-reference

#351 MGMT-20133: Avoid virtual device creation in live ISO mode
  data/scripts/bin/create-virtual-device.sh.template
Labels: approved, lgtm, jira/valid-reference

#349 MGMT-20131: Remove dependency on an external registry image
  .dockerignore
  Dockerfile.openshift-appliance
  docs/appliance-config.md
  docs/user-guide.md
  go.mod
  go.sum
  pkg/asset/config/appliance_config.go
  pkg/asset/data/data_iso.go
  pkg/consts/consts.go
  pkg/registry/registry.go
  pkg/skopeo/skopeo_test.go
  registry/Dockerfile.registry
  registry/config.yml
  registry/main.go
Labels: approved, lgtm, jira/valid-reference

#352 MGMT-20139: Support mirroring with a release image url
  data/services/bootstrap/pre-install-node-zero.service
  docs/appliance-config.md
  docs/user-guide.md
  pkg/asset/config/appliance_config.go
  pkg/asset/ignition/bootstrap_ignition.go
  pkg/asset/ignition/install_ignition.go
  pkg/asset/registry/registriesconf.go
  pkg/consts/consts.go
  pkg/release/release.go
  pkg/release/release_test.go
  pkg/templates/data.go
  pkg/templates/scripts/mirror/imageset.yaml.template
Labels: approved, jira/valid-reference

#354 AGENT-1140: support interactive flow in update-hosts
  data/scripts/bin/update-hosts.sh.template
  data/services/bootstrap/update-hosts.service
Labels: approved, jira/valid-reference

#357 Dockerfile: lock oc/oc-mirror versions
  Dockerfile.openshift-appliance
  artifacts.lock.yaml
Labels: approved

#355 MGMT-20172: Change the upgrade-iso command to remove the dependency on external registry
  pkg/asset/data/data_iso.go
  pkg/asset/upgrade/upgrade_iso.go
  pkg/registry/registry.go
Labels: approved, lgtm, jira/valid-reference

#358 AGENT-1140: fix error when no cluster is defined yet
  data/scripts/bin/update-hosts.sh.template
Labels: approved, lgtm, jira/valid-reference

#360 Tidy go mods
  go.mod
Labels: approved

#367 tekton: update hermetic
  .tekton/appliance-pull-request.yaml
  .tekton/appliance-push.yaml
  Dockerfile.openshift-appliance
  artifacts.lock.yaml
  rpm-prefetching/README.md
  rpm-prefetching/rpms.in.yaml
  rpm-prefetching/rpms.lock.yaml
Labels: approved
